### ISSUE TITLE
Perl::Critic: remove OTOBO::RequireTrueReturnValueForModules

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#13]
What is the benefit of having an OTOBO specific policy? What does it do differently than https://metacpan.org/pod/release/PETDANCE/Perl-Critic-1.138/lib/Perl/Critic/Policy/Modules/RequireEndWithOne.pm ?

**Comment by bschmalhofer** [comment]
I took a look at the latest run. Every violation was reported twice. So I think it is save to remove the OTOBO module.

[checked] Kernel/Output/Template/Provider.pm
[33mTidyAll::Plugin::OTOBO::Perl::PerlCritic[0m
[31mModules and tests have to return a true value ("1;") at line 1, column 1. Use "1;" as the last statement of the file.
 Module does not end with "1;" at line 324, column 1. Must end with a recognizable true value.[0m

**Comment by svenoe** [comment]
Taken notice of, agree - can be closed when it comes to me. :)

**Comment by bschmalhofer** [comment]
Module is removed. Closing this issue.
