### ISSUE TITLE
Make CodePolicy usable thoroughly (Step 1: Perl)

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/CodePolicy#2]
At the moment CodePolicy can already be used to correct code, but there are too many exceptions and unclear or undefined behavior. The goal should be to add CodePolicy to Bernhards compile-test upon pushing, maybe even replace it, as CodePolicy should check for syntax errors, too.

In the first step we should ignore ESLint, much of what is there is, from what I understand rather for OTRS7 and OTRS8, and it will need more time to really fit this to OTOBO.

Things I would like to have/change (please discuss):

- [x] Longer allowed lines. Codepolicy sometimes introduces line breaks which are really ugly, to me. - After short discussion and looking at it on different screens, I decided to go for 160 and enable -vmll (don't include beginning indentation of the code)
- [x] I like to write `$Hash{ $Key }` and `$Hash{Key}`, especially for something like `$Hash{ $Keys->{Example1}[0] }` this looks nicer to me, but CodePolicy doesn't make this distinctions and always removes the whitespaces. I would like to change that, if possible. - Doesn't seem possible with PerlTidy, not important enough to bother with it, further.
- [x] Same for other stuff: `for my $Module ( @ModuleList )` - see above

**Comment by svenoe** [comment]
Things not working right atm:

- [ ] Kernel/Output/HTML/Templates/Standard/Copyright.tt - swallowed a '-->' at 2020->2021 update

**Comment by svenoe** [comment]
At a later stage we should refine some stuff, I open another checklist, but just with the intention to copy it to another issue somewhen:

- [ ] Use ESLint.
- [ ] Provide a set of rules which allows unless only in non nested statements in Kernel/TidyAll/Plugin/OTOBO/Perl/Critic/Policy/OTOBO/ProhibitUnless.pm and enable the module again in Kernel/TidyAll/Plugin/OTOBO/Perl/PerlCritic.pm .

**Comment by bschmalhofer** [comment]
@svenoe : Regarding `my ( $Self, %Param ) = @_;` vs. `my $Self = shift; my %Param = @_;' . This is mostly a personal preference. The idea is that it is emphasised that the subroutine should be used as a method. In OTOBO this is not really importandl, as most subroutines are methods.
Most important is that the code is consistent, so I don't mind going back to the old usage.

**Comment by svenoe** [comment]
Ok, then I think we should do that, as I think the general check whether @_ is unpacked is good to have, and with the old version it is automatically covered by standard PerlCritic, and for your version we would have to write an module ourselves.

**Comment by svenoe** [comment]
We could think about using a newer version of PerlTidy to be able to use the flag -xci. (See https://metacpan.org/pod/perltidy#FORMATTING-OPTIONS - it didn't work and I assume it's a version problem.)
