### ISSUE TITLE
Perl::Critic: Think about the policy  OTOBO::RequireParensWithMethods

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#21]
I'm not happy about the policy `OTOBO::RequireParensWithMethods` . I think the trend is to allow plain method calls when there are no parameters to pass.

In my opinion
`            
my $SessionID     = $PlackRequest->cookies->{$SessionName};
my $OrigPath = $Req->path;
`
is nicer than
`
 my $SessionID     = $PlackRequest->cookies()->{$SessionName};
 my $OrigPath = $Req->path();
`

**Comment by StefanRother-OTOBO** [comment]
I am with Bernhard.

**Comment by svenoe** [comment]
I think I prefer the parenthesis, especially as we have a very consistent looking code at the moment, when it comes to this, and it is definitely something people newer to perl will stumble upon - but I can handle code without them, for the sake of trendiness. I leave the decision to you. :)

**Comment by bschmalhofer** [comment]
I have put OTOBO::RequireParensWithMethods on lowest severity. This means that the policy will be ignored unless explicitly activated.
Currently only two violations would be reported.

Closing this issue.
