### ISSUE TITLE
Perl::Critic: think about ProhibitUnrestrictedNoCritic and ProhibitUselessNoCritic

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#22]
The unrestricted 'no critic' leaves the developer wondering what the warning was.

https://metacpan.org/pod/Perl::Critic::Policy::Miscellanea::ProhibitUnrestrictedNoCritic

Useless 'no critic' are confusing. More importantly, the case when a warning disappears and then reappears again, should be brought to attention.
 
https://metacpan.org/pod/Perl::Critic::Policy::Miscellanea::ProhibitUselessNoCritic

**Comment by svenoe** [comment]
I think both are good additions.

**Comment by bschmalhofer** [comment]
I added the policies and got as expected many failures. The useless 'no critic' can be removed quickly. Let's how many unrestricted 'no critic' will then remain.

```
bes:~/devel/OTOBO/otobo (rel-10_0)$ grep UselessNoCritic  critic_20210208a.out  | wc -l
223
bes:~/devel/OTOBO/otobo (rel-10_0)$ grep UnrestrictedNoCritic  critic_20210208a.out  | wc -l
325

```

**Comment by bschmalhofer** [comment]
Looks like the OTOBO policies don't support restricted 'no critic' . Or the complete package name must be passed. Must be investigated.

```
bes:~/devel/OTOBO/otobo (issue-rotheross/CodePolicy#22-no_critic)$ ../CodePolicy/bin/otobo.CodePolicy.pl  --plugins +TidyAll::Plugin::OTOBO::Perl::PerlCritic --processes 1 -f Kernel/Config/Defaults.pm 
Found OTOBO version 10.0.
This module seems to be copyrighted by Rother OSS GmbH. File copyright will automatically be assigned to Rother OSS GmbH.
  If this is not correct, you can change the <Vendor> tag in your SOPM.
[checked] Kernel/Config/Defaults.pm
TidyAll::Plugin::OTOBO::Perl::PerlCritic
OTOBO::ProhibitOpen violated at line 2019 column 10 (Severity: 5)
  Use of "open" is not allowed to read or write files
Use MainObject::FileRead() or FileWrite() instead

Error: 1 file(s) did not pass validation.
 - Kernel/Config/Defaults.pm

bes:~/devel/OTOBO/otobo (issue-rotheross/CodePolicy#22-no_critic)$ grep ProhibitOpen Kernel/Config/Defaults.pm 
    if ( open( my $Product, '<', "$Self->{Home}/RELEASE" ) ) { ## no critic qw(InputOutput::RequireBriefOpen OTOBO::ProhibitOpen)
```

**Comment by bschmalhofer** [comment]
Also looks like Miscellanea::ProhibitUselessNoCritic is broken. Unrestricted 'no critic' are not reported when the declaration is not restricted.

**Comment by bschmalhofer** [comment]
The unrestricted 'no critic' are gone now. Either removed completely or substituted by a declaration with restriction to specific modules. There is still a number of useless 'no critic'. These are due to that the OTOBO policies do not honor the restricted 'no critic' declarations,

TODO:

- [ ] investigate why 'no critic qw(OTOBO::ProhibitOpen)' does not work
- [ ] Provide a pull request to the standard policy Miscellanea::ProhibitUselessNoCritic

**Comment by bschmalhofer** [comment]
The PR https://github.com/Perl-Critic/Perl-Critic/pull/940 has been created for the issue https://github.com/Perl-Critic/Perl-Critic/issues/939. 
Actually, the fix in Perl::Critic does not matter to OTOBO any more, as the unrestricted 'no critic' annotations are gone now. Closing this issue.
