### ISSUE TITLE
Perl::Critic: OTOBOProhibitOpen does not report all calls to open

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#26]
The description of OTOBOProhibitOpen says: _Use of "open" is not allowed._ . But the implementation only checks for three argument open with the mode either '<' or '>'. This does not compute. 

An effect is that the  line 384 from Kernel/System/Main.pm is not reported:

 `if ( !open $FH, $Mode, $Param{Location} ) {
`

**Comment by svenoe** [comment]
Fixed.

**Comment by svenoe** [comment]
...now...
