### ISSUE TITLE
Require current versions of the used  Perl tools

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#3]
In CodePolicy.sopm following versions are required:
 
```
   <ModuleRequired Version="0.17">Code::TidyAll</ModuleRequired>
    <ModuleRequired>Perl::Critic</ModuleRequired>

```
The packaged version of Perl::Tidy is fairly recent, but there have been significant improvements since then.

I see no benefit in supporting old versions of the tools. Code::TidyAll 0.17 is from 2013.

I propose:

- [ ] Require the current versions of Code::TidyAll, Perl::Critic, and Perl::Tidy in CodePolicy.sopm
- [ ] Require the current version of PPI
- [ ] No longer package Perl::Tidy in Kernel/cpan-lib,  (remove Kernel/cpan-lib from @INC)
- [ ] Provide a _cpanfile_ for local installations of CodePolicy
- [ ] Add the feature 'devel:codepolicy' in bin/otobo.CheckModules.pl for OTOBO 10.0.8
- [ ] Include 'devel:codepolicy' either in the OTOBO Docker image or in a dedicated container

Non-Perl related tools should be handled in separate issues.

**Comment by svenoe** [comment]
From Kernel/TidyAll/Plugin/OTOBO/Perl/PerlTidy.pm:

` 28 # TODO: Latest release 20190915 of Perl::Tidy seems to be buggy about vertical indentation.
 29 #   Force a certain version for now.`

**Comment by bschmalhofer** [comment]
@svenoe Looking at https://metacpan.org/changes/distribution/Perl-Tidy I found that there were some fixes regarding vertical alignment since 2019. I suggest that we go for it, that is testing what the effects are on the OTOBO code.

**Comment by svenoe** [comment]
Did some tidying with PerlTidy 20210111 - results look good to me, there are quite some changes though, and I only looked at maybe 30 or 40 files. Will write more on this tomorrow.

**Comment by svenoe** [comment]
Code::TidyAll - the version-statement of the sopm is a minimum version. I will update it to 0.56, which is actually required in the code. This is still old, but I don't see the point in requiring a newer version, if everything works with the old ones. I ran CodePolicy on Kernel/System/Ticket today (I admit, a rather small sample), and saw no changes with 0.78 (the newest) version. (In the end the installed version of the system will be used, and if it works, why force the user to install a newer one.)

**Comment by svenoe** [comment]
Perl::Critic - I don't see an explicit version used. I think until someone using some old system runs into a bug or so, we can leave it at that.

**Comment by svenoe** [comment]
PPI should for most cases be dealt with use v5.24, I assume?

I propose to close this issue and discuss the handling of Perl::Tidy (cpan-lib vs cpanfile, CheckModules,...) in another issue.

**Comment by bschmalhofer** [comment]
@svenoe PPI is a regular CPAN module, not tied to the Perl interpreter. But we don't have to worry about the version of PPI, as Perl::Critic already requires a minimum version of that module.

**Comment by svenoe** [comment]
>     * [ ]  No longer package Perl::Tidy in Kernel/cpan-lib,  (remove Kernel/cpan-lib from @inc)
> 
>     * [ ]  Provide a _cpanfile_ for local installations of CodePolicy
> 
>     * [ ]  Add the feature 'devel:codepolicy' in bin/otobo.CheckModules.pl for OTOBO 10.0.8
> 
>     * [ ]  Include 'devel:codepolicy' either in the OTOBO Docker image or in a dedicated container

Kommt in ein neues Issue
