### ISSUE TITLE
Configure ignores for the policy  OTOBO::Perl::ParamObject

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#44]
In otobo rel-10_0 branch there are 4 complaints about OTOBO::Perl::ParamObject being violated. In rel-10_1 there migtht be more violations. This can be improved.

TODO:

- [x] Check in the rel-10_1 branch whether to usage of Kernel::System::Web::Request is warranted
- [x] Update the ignore list

**Comment by bschmalhofer** [comment]
Ignore almost all violations of OTOBO::Perl::ParamObject.
Don't ignore the violations from event modules, as I'm not sure that these usages are warrated.
The new CodePolicy run looks fine. Closing this issue.

**Comment by svenoe** [comment]
This is not clear for me at least. I will reopen the issue for now as a reminder.

**Comment by svenoe** [comment]
Misunderstood at first. I still would prefer exceptions on directory level (the rc file) only if it's really warranted (e.g. Kernel/System/Web), and else use ## no critic that it's also clear in the code, that something special is going on there. I will check all occurrences.

As discussed, we could think about standardizing the return of Web::Request information for log entries.

**Comment by bschmalhofer** [comment]
Another case, where the ParamObject is used, is the _Kernel/System/Auth/Sync/LDAP.pm_ in the rel-10_1 branch. With the current setting in _tidyallrc_ this usage is flagged, but maybe warranted.

**Comment by bschmalhofer** [comment]
Hi @svenoe,

I propose to allow usage of the ParamObject in _Kernel/System/Web_ and in the authentication related modules.

> [+TidyAll::Plugin::OTOBO::Perl::ParamObject]
> select = **/*.{pl,psgi}
> select = Kernel/System/**/*.pm Custom/Kernel/System/**/*.pm
> ignore = Kernel/System/Auth/**/*.pm Custom/Kernel/System/Auth/**//*.pm
> ignore = Kernel/System/AuthSession/**/*.pm Custom/Kernel/System/AuthSession/**/*.pm
> ignore = Kernel/System/CustomerAuth/**/*.pm Custom/Kernel/System/CustomerAuth/**/*.pm
> ignore = Kernel/System/Web/**/*.pm Custom/Kernel/System/Web/**/*.pm

**Comment by bschmalhofer** [comment]
With the changed TidyAll config for OTOBO::Perl::ParamObject we need to check for violations in the rel-10_0 branch.

**Comment by bschmalhofer** [comment]
With the changed TidyAll config for OTOBO::Perl::ParamObject we need to check for violations in the rel-10_1 branch.

**Comment by bschmalhofer** [comment]
Let's stick with the further simplified config. Closing this issue.
```
[+TidyAll::Plugin::OTOBO::Perl::ParamObject]
select = **/*.{pl,psgi}
select = Kernel/System/**/*.pm Custom/Kernel/System/**/*.pm
ignore = Kernel/System/Web/**/*.pm Custom/Kernel/System/Web/**/*.pm

```
