### ISSUE TITLE
Reenable the Prohibit-Unless-check

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#5]
This time using Perl::Critic::Policy::ControlStructures::ProhibitUnlessBlocks , as Postfix unless should be allowed.

TODO:

- [x] explicitly enable the policy

**Comment by bschmalhofer** [comment]
Tested the change by adding a block unless in Kernel/System/Time.pm.
No violation reported from the master branch.
Violation reported from the issue-#5-block_unless branch.
Did some tidying. Had to allow 'use v5.24' in the SyntaxCheck policy, so that 'state' is no syntax error.
Removed the OTOBO policy Unless for good.
Closing this issue.

**Comment by bschmalhofer** [comment]
Reopen because https://metacpan.org/release/Perl-Critic/source/lib/Perl/Critic/Policy/ControlStructures/ProhibitPostfixControls.pm should be activated too.

**Comment by svenoe** [comment]
We should check the usage of the latter before activating it. If half of OTOBO is affected, I'm for postponing it at least.

**Comment by bschmalhofer** [comment]
I have looked into the policy ControlStructures::ProhibitPostfixControls. This policy should be able to check that 'unless' is used only for flow control. Restriction the postfix element to 'unless' works. But allowing 'unless' after a return does not work. I consider this as a bug.
The releavant lines in the policy are:

```
 # Handle special cases
    my $content = $elem->content();
    if ($content eq 'if' or $content eq 'when') {
        # Postfix 'if' allowed with loop breaks, or other
        # flow-controls like 'die', 'warn', and 'croak'
        return if $stmnt->isa('PPI::Statement::Break');
        return if defined $self->{_flowcontrol}{ $stmnt->schild(0)->content() };
    }
```
Here *unless' is not special cased. This means that there will be a violation for the common idiom:

`return 1 unless $Content =~ m{<otrs_config.*?version="2.0"};`

So, let's keep ControlStructures::ProhibitPostfixControls deactivated.

**Comment by bschmalhofer** [comment]
Giving up on ControlStructures::ProhibitPostfixControls . Postfix 'unless' is now generally allowd. Closing this issue.
