### ISSUE TITLE
Do not force line rewrap before perltidy.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/CodePolicy#52]
With our longer allowed length of lines, sometimes it is nicer to wrap things manually. In principle we can just remove lines 59 and 61 of Kernel/TidyAll/Plugin/OTOBO/Perl/PerlTidy.pm.

I did not do this yet, because I think it would be nice to at least keep this as an option. (My idea is, that the relevant check which decides whether a pull request is ok or not, is done without, but people still have the possibility to start CodePolicy manually with, I don't know, --rewrap, to be able to easily adapt old package files e.g..) Not sure how to handle this nicely in `sub transform_source` though - @bschmalhofer do you have a good idea? If not, I'm for just commenting it out for now.

As additional info: Running Codepolicy first without and then with rewrap on Kernel/GenericInterface and Kernel/Modules didn't result in any differences (which is expected, since I aleady ran it on Kernel completely in https://github.com/RotherOSS/otobo/commit/d2d6be92c1665473091303dbf300e0c830d6d9be (sorry if I destroyed something...^^')).

**Comment by svenoe** [comment]
Also, off topic, with this change implemented, I would release the next version of CodePolicy and start to use it in an automated fashion.

**Comment by bschmalhofer** [comment]
Removed the statements that force rewrapping. Running the CodePolicy on the otobo repository showed sane diffs. Closing this issue.

**Comment by svenoe** [comment]
Na gut, dann halt ganz raus...^^
