### ISSUE TITLE
Make InputOutput::RequireBriefOpen less stringent

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/CodePolicy#60]
The policy https://metacpan.org/pod/Perl::Critic::Policy::InputOutput::RequireBriefOpen is not really earth shattering. E.g. the following code is tagged with the current settings:

```
        if ( open my $ViewerDataFH, '>', $Filename ) {    ## no critic qw(OTOBO::ProhibitOpen)
            print $ViewerDataFH $Data{Content};
        }
        else {

            # log error
            $LogObject->Log(
                Priority => 'error',
                Message  => "Cant write $Filename: $!",
            );

            return $LayoutObject->ErrorScreen();
        }

```
That the file handle is closed the latest at the return looks good to me, but the return happens to be 11 lines from the open call, instead of 9. I propose the extend the permitted number of lines to 20, that is about half a page.

**Comment by bschmalhofer** [comment]
Actually this change seems to make no difference on the OTOBO source. This might be due to the many false positives of the policy InputOutput::RequireBriefOpen. See e.g. https://github.com/Perl-Critic/Perl-Critic/issues/611.
Still I propose to merge the commit.

**Comment by bschmalhofer** [comment]
PR has been merged. Closing the issue.

**Comment by svenoe** [comment]
I agree, this made me wonder a bit, from time, to time, too... :)
